name: update_documentation

on:
  repository_dispatch:
    types: [community-ui-prerelease]

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Update package.json @selfcommunity/types dependency
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: dependencies.@selfcommunity/types
          value: "^${{ github.event.client_payload.types }}"
      - name: Update package.json @selfcommunity/utils dependency
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: dependencies.@selfcommunity/utils
          value: "^${{ github.event.client_payload.utils }}"
      - name: Update package.json @selfcommunity/api-services dependency
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: dependencies.@selfcommunity/api-services
          value: "^${{ github.event.client_payload.api-services }}"
      - name: Update package.json @selfcommunity/react-i18n dependency
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: dependencies.@selfcommunity/react-i18n
          value: "^${{ github.event.client_payload.i18n }}"
      - name: Update package.json @selfcommunity/react-core dependency
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: dependencies.@selfcommunity/react-core
          value: "^${{ github.event.client_payload.core }}"
      - name: Update package.json @selfcommunity/react-ui dependency
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: dependencies.@selfcommunity/react-ui
          value: "^${{ github.event.client_payload.ui }}"
      - name: Update package.json @selfcommunity/react-templates dependency
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: dependencies.@selfcommunity/react-templates
          value: "^${{ github.event.client_payload.templates }}"
      - name: Update community-ui submodule
        run: |
          git config --global user.email "team@quentral.com"
          git config --global user.name "quentralhub"
          rm -rf sdk/community-js/
          git submodule update
          git add sdk/community-js/
          git add package.json
          git commit -m 'update package.json and gitlink to community-js'
          git push
